logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: "DEBUG"
server:
  port: 8081
#sdasg
spring:
  data:
    mongodb:
      host: 3.6.90.240
      port: 27017
      database: NulinePublic
