logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: "DEBUG"
server:
  port: 8081
#sdasg
spring:
  data:
    mongodb:
      #uri: mongodb://ec2-13-232-9-97.ap-south-1.compute.amazonaws.com/NulinePublic
      uri: mongodb://localhost:27017/NulinePublic
